In [2]:
import pandas as pd
import numpy as np
asset = pd.read_csv(r"D:/Git/algo trading/reports/asset_performance_leaderboard.csv")
global_summary = pd.read_csv(r"D:/Git/algo trading/reports/global_strategy_summary.csv")

In [3]:
asset

,Ticker,Strategy,Total_Return_%,Trades,Win_Rate_%,Profit_Factor,Avg_Win_Return_pct,Avg_Loss_Return_pct,Win_Loss_Ratio,Max_Drawdown_pct,...,Short_Total_Return_%,Short_Trades,Short_Win_Rate_%,Short_Profit_Factor,Short_Avg_Win_Return_pct,Short_Avg_Loss_Return_pct,Short_Win_Loss_Ratio,Short_Max_Drawdown_pct,Short_Sharpe_Ratio,Short_Recovery_Factor
0,MAZDOCK,Momentum_20,877.49,716,52.09,1.364,2.78,-2.24,1.243,-45.91,...,-51.44,275,50.18,0.824,1.98,-2.44,0.812,-52.30,-0.774,-0.984
1,MAZDOCK,Trend_Filter,820.78,1038,51.54,1.269,2.48,-2.10,1.179,-48.36,...,-45.13,489,51.94,0.917,1.77,-2.12,0.838,-48.03,-0.519,-0.940
2,COCHINSHIP,Trend_Filter,739.53,1038,51.16,1.265,2.40,-2.01,1.193,-42.66,...,-30.21,523,51.24,0.968,1.86,-2.06,0.903,-46.66,-0.319,-0.647
3,FACT,Momentum_20,697.86,725,51.45,1.328,2.84,-2.29,1.239,-45.29,...,-25.16,321,52.02,0.974,2.26,-2.57,0.880,-43.62,-0.279,-0.577
4,BSE,Momentum_20,580.33,757,54.69,1.317,2.31,-2.14,1.078,-52.15,...,-53.68,287,50.87,0.812,1.88,-2.41,0.779,-69.53,-0.836,-0.772
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6957,CGCL,Momentum_20,-87.09,421,43.94,0.629,1.67,-2.10,0.796,-89.94,...,-67.97,209,49.28,0.628,1.64,-2.53,0.646,-68.45,-1.202,-0.993
6958,MOTILALOFS,Trend_Filter,-87.62,1038,51.93,0.904,1.88,-2.26,0.830,-91.91,...,-72.60,655,53.13,0.849,1.70,-2.29,0.739,-79.52,-0.909,-0.913
6959,GPIL,Trend_Filter,-87.62,1038,50.48,0.916,1.93,-2.19,0.884,-93.94,...,-69.78,644,50.78,0.862,1.83,-2.22,0.823,-81.73,-0.847,-0.854
6960,SAMMAANCAP,Trend_Filter,-88.23,1038,47.59,0.860,2.09,-2.23,0.935,-91.96,...,-76.08,721,49.65,0.868,2.03,-2.35,0.866,-83.67,-0.826,-0.909
6961,CGCL,Trend_Filter,-90.65,1038,50.00,0.852,1.50,-1.79,0.840,-93.04,...,-60.57,677,53.91,0.902,1.55,-2.04,0.761,-61.84,-0.543,-0.979

In [4]:
global_summary

,Strategy,Avg_Return_Per_Asset_pct,Median_Return_pct,Total_Trades_Executed,Profitable_Assets_Count,Average_Win_Rate_pct,Global_Profit_Factor,Avg_Win_Return_pct,Avg_Loss_Return_pct,Win_Loss_Ratio,...,Short_Average_Win_Rate_pct,Short_Global_Profit_Factor,Short_Avg_Win_Return_pct,Short_Avg_Loss_Return_pct,Short_Win_Loss_Ratio,Short_Max_Drawdown_pct,Short_Sharpe_Ratio,Short_Recovery_Factor,Short_Profitable_Assets_Count,Short_Market_Coverage_Hit_Rate_pct
0,Momentum_20,31.65,2.71,245478,250,49.78,1.058,1.80,-1.71,1.049,...,49.92,0.915,1.69,-1.91,0.901,-82.59,-0.591,-0.321,91,19.12
1,Trend_Filter,6.15,-15.62,441732,185,49.84,1.011,1.62,-1.62,1.002,...,50.03,0.906,1.50,-1.71,0.889,-89.83,-0.641,-0.600,40,8.40
2,Volume_Spike,8.23,4.50,22263,268,48.61,1.281,2.44,-2.00,1.266,...,0.00,0.000,0.00,0.00,0.000,0.00,0.000,0.000,0,0.00
3,Turtle_Breakout,11.86,3.28,26387,286,49.67,1.266,2.02,-1.65,1.221,...,0.00,0.000,0.00,0.00,0.000,0.00,0.000,0.000,0,0.00
4,EMA21_Mean_Reversion,-3.07,-2.32,57743,217,50.67,1.025,1.82,-1.95,0.966,...,50.46,0.950,1.64,-2.02,0.873,-90.25,-0.822,-0.013,171,35.92
5,MACD_Histogram_Momentum,6.81,3.64,17757,290,49.85,1.348,1.85,-1.52,1.264,...,0.00,0.000,0.00,0.00,0.000,0.00,0.000,0.000,0,0.00
6,Volatility_Breakout,6.67,2.17,11711,267,48.94,1.411,2.52,-1.92,1.364,...,0.00,0.000,0.00,0.00,0.000,0.00,0.000,0.000,0,0.00
7,Bollinger_Mean_Reversion,3.44,1.98,11331,267,49.52,1.384,1.87,-1.58,1.266,...,0.00,0.000,0.00,0.00,0.000,0.00,0.000,0.000,0,0.00
8,Support_Bounce,6.21,5.82,9827,330,52.23,1.852,1.79,-1.38,1.413,...,0.00,0.000,0.00,0.00,0.000,0.00,0.000,0.000,0,0.00
9,EMA_Crossover,5.04,3.63,9595,313,50.77,1.685,1.85,-1.42,1.395,...,0.00,0.000,0.00,0.00,0.000,0.00,0.000,0.000,0,0.00
10,RSI_Overbought,-2.02,-1.36,9026,202,49.18,1.166,1.70,-1.87,1.034,...,49.18,1.166,1.70,-1.87,1.034,-38.64,-1.333,0.371,202,42.44
11,RSI_Oversold,3.34,2.56,5086,316,53.30,2.717,2.07,-1.67,1.572,...,0.00,0.000,0.00,0.00,0.000,0.00,0.000,0.000,0,0.00
12,BB_Squeeze_Breakout,1.76,0.50,4087,251,49.35,2.256,2.02,-1.63,1.622,...,0.00,0.000,0.00,0.00,0.000,0.00,0.000,0.000,0,0.00
13,SuperTrend_Mimic,0.34,-0.55,1373,180,46.18,2.246,3.42,-2.85,1.409,...,0.00,0.000,0.00,0.00,0.000,0.00,0.000,0.000,0,0.00
14,Golden_Cross,0.22,0.14,1214,226,51.48,5.470,1.27,-1.18,2.531,...,0.00,0.000,0.00,0.00,0.000,0.00,0.000,0.000,0,0.00