In [6]:
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
import numpy as np
asset = pd.read_csv(r"D:/Git/Algo_trading/reports/asset_performance_leaderboard.csv")
global_summary = pd.read_csv(r"D:/Git/Algo_trading/reports/global_strategy_summary.csv")

In [10]:
global_summary

,Strategy,Avg_Return_Per_Asset_pct,Median_Return_pct,Total_Trades_Executed,Profitable_Assets_Count,Average_Win_Rate_pct,Global_Profit_Factor,Avg_Win_Return_pct,Avg_Loss_Return_pct,Win_Loss_Ratio,Sharpe_Ratio,Recovery_Factor,Max_Drawdown_pct,Market_Coverage_Hit_Rate_pct,Long_Avg_Return_Per_Asset_pct,Long_Median_Return_pct,Long_Total_Trades_Executed,Long_Average_Win_Rate_pct,Long_Global_Profit_Factor,Long_Avg_Win_Return_pct,Long_Avg_Loss_Return_pct,Long_Win_Loss_Ratio,Long_Max_Drawdown_pct,Long_Sharpe_Ratio,Long_Recovery_Factor,Long_Profitable_Assets_Count,Long_Market_Coverage_Hit_Rate_pct,Short_Avg_Return_Per_Asset_pct,Short_Median_Return_pct,Short_Total_Trades_Executed,Short_Average_Win_Rate_pct,Short_Global_Profit_Factor,Short_Avg_Win_Return_pct,Short_Avg_Loss_Return_pct,Short_Win_Loss_Ratio,Short_Max_Drawdown_pct,Short_Sharpe_Ratio,Short_Recovery_Factor,Short_Profitable_Assets_Count,Short_Market_Coverage_Hit_Rate_pct
0,Momentum_20,31.65,2.71,245478,250,49.78,1.058,1.80,-1.71,1.049,0.007,1.249,-89.94,52.52,73.05,28.73,145502,49.68,1.187,1.88,-1.58,1.181,-85.56,0.259,3.665,353,74.16,-18.94,-20.16,99976,49.92,0.915,1.69,-1.91,0.901,-82.59,-0.591,-0.321,91,19.12
1,Trend_Filter,6.15,-15.62,441732,185,49.84,1.011,1.62,-1.62,1.002,-0.135,0.347,-93.94,38.87,84.78,33.75,203055,49.61,1.156,1.77,-1.51,1.159,-82.36,0.306,3.670,332,69.75,-37.49,-42.90,238677,50.03,0.906,1.50,-1.71,0.889,-89.83,-0.641,-0.600,40,8.40
2,Volume_Spike,8.23,4.50,22263,268,48.61,1.281,2.44,-2.00,1.266,-0.421,1.331,-73.13,56.30,8.23,4.50,22263,48.61,1.281,2.44,-2.00,1.266,-73.13,-0.421,1.331,268,56.30,0.00,0.00,0,0.00,0.000,0.00,0.00,0.000,0.00,0.000,0.000,0,0.00
3,Turtle_Breakout,11.86,3.28,26387,286,49.67,1.266,2.02,-1.65,1.221,-0.423,1.529,-83.98,60.08,11.86,3.28,26387,49.67,1.266,2.02,-1.65,1.221,-83.98,-0.423,1.529,286,60.08,0.00,0.00,0,0.00,0.000,0.00,0.00,0.000,0.00,0.000,0.000,0,0.00
4,EMA21_Mean_Reversion,-3.07,-2.32,57743,217,50.67,1.025,1.82,-1.95,0.966,-0.476,0.350,-89.52,45.59,8.41,6.59,21245,51.03,1.329,2.12,-1.84,1.194,-63.04,-0.455,1.124,327,68.70,-10.41,-7.30,36498,50.46,0.950,1.64,-2.02,0.873,-90.25,-0.822,-0.013,171,35.92
5,MACD_Histogram_Momentum,6.81,3.64,17757,290,49.85,1.348,1.85,-1.52,1.264,-0.673,1.204,-38.37,60.92,6.81,3.64,17757,49.85,1.348,1.85,-1.52,1.264,-38.37,-0.673,1.204,290,60.92,0.00,0.00,0,0.00,0.000,0.00,0.00,0.000,0.00,0.000,0.000,0,0.00
6,Volatility_Breakout,6.67,2.17,11711,267,48.94,1.411,2.52,-1.92,1.364,-0.696,1.405,-41.54,56.09,6.67,2.17,11711,48.94,1.411,2.52,-1.92,1.364,-41.54,-0.696,1.405,267,56.09,0.00,0.00,0,0.00,0.000,0.00,0.00,0.000,0.00,0.000,0.000,0,0.00
7,Bollinger_Mean_Reversion,3.44,1.98,11331,267,49.52,1.384,1.87,-1.58,1.266,-0.978,1.091,-30.70,56.09,3.44,1.98,11331,49.52,1.384,1.87,-1.58,1.266,-30.70,-0.978,1.091,267,56.09,0.00,0.00,0,0.00,0.000,0.00,0.00,0.000,0.00,0.000,0.000,0,0.00
8,Support_Bounce,6.21,5.82,9827,330,52.23,1.852,1.79,-1.38,1.413,-0.979,1.791,-32.03,69.33,6.21,5.82,9827,52.23,1.852,1.79,-1.38,1.413,-32.03,-0.979,1.791,330,69.33,0.00,0.00,0,0.00,0.000,0.00,0.00,0.000,0.00,0.000,0.000,0,0.00
9,EMA_Crossover,5.04,3.63,9595,313,50.77,1.685,1.85,-1.42,1.395,-1.061,1.575,-46.26,65.76,5.04,3.63,9595,50.77,1.685,1.85,-1.42,1.395,-46.26,-1.061,1.575,313,65.76,0.00,0.00,0,0.00,0.000,0.00,0.00,0.000,0.00,0.000,0.000,0,0.00
10,RSI_Overbought,-2.02,-1.36,9026,202,49.18,1.166,1.70,-1.87,1.034,-1.333,0.371,-38.64,42.44,0.00,0.00,0,0.00,0.000,0.00,0.00,0.000,0.00,0.000,0.000,0,0.00,-2.02,-1.36,9026,49.18,1.166,1.70,-1.87,1.034,-38.64,-1.333,0.371,202,42.44
11,RSI_Oversold,3.34,2.56,5086,316,53.30,2.717,2.07,-1.67,1.572,-1.445,2.466,-28.76,66.39,3.34,2.56,5086,53.30,2.717,2.07,-1.67,1.572,-28.76,-1.445,2.466,316,66.39,0.00,0.00,0,0.00,0.000,0.00,0.00,0.000,0.00,0.000,0.000,0,0.00
12,BB_Squeeze_Breakout,1.76,0.50,4087,251,49.35,2.256,2.02,-1.63,1.622,-1.900,1.919,-28.84,52.73,1.76,0.50,4087,49.35,2.256,2.02,-1.63,1.622,-28.84,-1.900,1.919,251,52.73,0.00,0.00,0,0.00,0.000,0.00,0.00,0.000,0.00,0.000,0.000,0,0.00
13,SuperTrend_Mimic,0.34,-0.55,1373,180,46.18,2.246,3.42,-2.85,1.409,-2.944,1.734,-46.03,37.82,0.34,-0.55,1373,46.18,2.246,3.42,-2.85,1.409,-46.03,-2.944,1.734,180,37.82,0.00,0.00,0,0.00,0.000,0.00,0.00,0.000,0.00,0.000,0.000,0,0.00
14,Golden_Cross,0.22,0.14,1214,226,51.48,5.470,1.27,-1.18,2.531,-8.444,1.562,-12.08,47.48,0.22,0.14,1214,51.48,5.470,1.27,-1.18,2.531,-12.08,-8.444,1.562,226,47.48,0.00,0.00,0,0.00,0.000,0.00,0.00,0.000,0.00,0.000,0.000,0,0.00

In [9]:
asset.head(100)

,Ticker,Strategy,Total_Return_%,Trades,Win_Rate_%,Profit_Factor,Avg_Win_Return_pct,Avg_Loss_Return_pct,Win_Loss_Ratio,Max_Drawdown_pct,Sharpe_Ratio,Recovery_Factor,Long_Total_Return_%,Long_Trades,Long_Win_Rate_%,Long_Profit_Factor,Long_Avg_Win_Return_pct,Long_Avg_Loss_Return_pct,Long_Win_Loss_Ratio,Long_Max_Drawdown_pct,Long_Sharpe_Ratio,Long_Recovery_Factor,Short_Total_Return_%,Short_Trades,Short_Win_Rate_%,Short_Profit_Factor,Short_Avg_Win_Return_pct,Short_Avg_Loss_Return_pct,Short_Win_Loss_Ratio,Short_Max_Drawdown_pct,Short_Sharpe_Ratio,Short_Recovery_Factor
0,MAZDOCK,Momentum_20,877.49,716,52.09,1.364,2.78,-2.24,1.243,-45.91,1.254,19.113,1912.84,441,53.29,1.779,3.26,-2.11,1.544,-26.94,1.821,71.004,-51.44,275,50.18,0.824,1.98,-2.44,0.812,-52.30,-0.774,-0.984
1,MAZDOCK,Trend_Filter,820.78,1038,51.54,1.269,2.48,-2.10,1.179,-48.36,1.163,16.972,1578.14,549,51.18,1.581,3.11,-2.09,1.491,-32.37,1.637,48.753,-45.13,489,51.94,0.917,1.77,-2.12,0.838,-48.03,-0.519,-0.940
2,COCHINSHIP,Trend_Filter,739.53,1038,51.16,1.265,2.40,-2.01,1.193,-42.66,1.146,17.335,1102.97,515,51.07,1.576,2.94,-1.95,1.505,-32.28,1.524,34.169,-30.21,523,51.24,0.968,1.86,-2.06,0.903,-46.66,-0.319,-0.647
3,FACT,Momentum_20,697.86,725,51.45,1.328,2.84,-2.29,1.239,-45.29,1.116,15.409,966.13,404,50.99,1.664,3.31,-2.08,1.591,-26.63,1.427,36.280,-25.16,321,52.02,0.974,2.26,-2.57,0.880,-43.62,-0.279,-0.577
4,BSE,Momentum_20,580.33,757,54.69,1.317,2.31,-2.14,1.078,-52.15,1.159,11.128,1368.60,470,57.02,1.755,2.54,-1.95,1.303,-26.23,1.880,52.177,-53.68,287,50.87,0.812,1.88,-2.41,0.779,-69.53,-0.836,-0.772
5,SUZLON,Momentum_20,538.71,778,50.51,1.274,2.70,-2.37,1.138,-43.52,1.084,12.379,423.33,448,49.11,1.402,3.04,-2.24,1.358,-40.63,1.122,10.419,22.05,330,52.42,1.102,2.25,-2.57,0.879,-30.47,0.104,0.724
6,ZENTEC,Momentum_20,523.37,662,48.79,1.321,2.80,-2.04,1.370,-41.39,1.109,12.645,747.75,441,49.43,1.606,2.88,-1.77,1.628,-27.65,1.520,27.044,-26.47,221,47.51,0.943,2.64,-2.58,1.023,-58.93,-0.379,-0.449
7,IFCI,Momentum_20,496.58,793,49.05,1.257,2.91,-2.44,1.193,-38.97,0.983,12.743,397.29,450,45.78,1.366,3.59,-2.38,1.506,-38.11,0.968,10.425,19.97,343,53.35,1.092,2.14,-2.52,0.848,-33.51,0.082,0.596
8,RVNL,Momentum_20,475.21,685,51.53,1.312,2.62,-2.18,1.205,-45.47,1.006,10.451,479.96,407,49.39,1.492,3.15,-2.10,1.500,-37.16,1.104,12.916,-0.82,278,54.68,1.042,1.93,-2.31,0.836,-37.16,-0.122,-0.022
9,COCHINSHIP,Momentum_20,470.49,752,50.80,1.280,2.58,-2.10,1.230,-34.85,1.029,13.500,781.92,462,51.95,1.561,2.85,-1.99,1.437,-25.41,1.438,30.772,-35.31,290,48.97,0.909,2.12,-2.27,0.935,-54.59,-0.518,-0.647
10,IRFC,Trend_Filter,465.31,1038,49.13,1.275,1.93,-1.56,1.233,-46.34,1.041,10.041,506.58,413,48.43,1.570,2.85,-1.76,1.617,-37.75,1.215,13.419,-6.80,625,49.60,1.013,1.33,-1.42,0.938,-32.12,-0.186,-0.212
11,TARIL,Momentum_20,450.65,741,52.90,1.231,3.12,-2.87,1.087,-40.56,0.932,11.111,768.52,487,52.57,1.424,3.34,-2.62,1.274,-28.96,1.290,26.537,-36.60,254,53.54,0.936,2.70,-3.35,0.805,-56.89,-0.382,-0.643
12,TITAGARH,Momentum_20,441.96,768,51.17,1.271,2.45,-2.05,1.197,-31.33,1.045,14.107,386.14,476,50.63,1.411,2.60,-1.91,1.364,-32.44,1.114,11.903,11.48,292,52.05,1.074,2.22,-2.29,0.968,-37.18,-0.009,0.309
13,RVNL,Trend_Filter,407.35,1038,49.90,1.220,2.32,-1.96,1.185,-49.46,0.904,8.236,753.53,497,48.69,1.507,3.07,-1.96,1.563,-37.32,1.297,20.191,-40.56,541,51.02,0.932,1.66,-1.95,0.851,-50.40,-0.470,-0.805
14,GVT&D,Momentum_20,369.95,699,51.36,1.254,2.59,-2.20,1.177,-44.42,0.983,8.328,1302.96,535,54.02,1.600,2.67,-1.97,1.357,-29.48,1.829,44.198,-66.50,164,42.68,0.607,2.24,-2.80,0.798,-68.12,-1.547,-0.976
15,SCHNEIDER,Trend_Filter,359.10,1038,49.13,1.192,2.39,-1.95,1.227,-67.13,0.900,5.349,758.23,575,49.22,1.460,2.71,-1.80,1.501,-44.18,1.462,17.162,-46.51,463,49.03,0.911,2.00,-2.13,0.939,-56.13,-0.567,-0.829
16,ADANIPOWER,Momentum_20,354.13,694,53.75,1.264,2.46,-2.28,1.078,-55.82,0.922,6.344,498.20,432,51.62,1.491,2.77,-2.01,1.377,-31.15,1.247,15.994,-24.08,262,57.25,0.961,1.99,-2.78,0.718,-61.97,-0.325,-0.389
17,SCHNEIDER,Momentum_20,335.18,746,49.06,1.244,2.51,-1.96,1.281,-47.42,0.939,7.068,603.08,470,50.43,1.513,2.70,-1.82,1.481,-39.06,1.435,15.440,-38.10,276,46.74,0.886,2.18,-2.19,0.996,-44.80,-0.614,-0.851
18,SWANCORP,Momentum_20,323.27,780,49.87,1.231,2.52,-2.06,1.225,-59.01,0.876,5.478,209.69,425,47.29,1.324,2.73,-1.87,1.463,-41.35,0.822,5.071,36.67,355,52.96,1.130,2.30,-2.32,0.992,-41.68,0.207,0.880
19,TRENT,Trend_Filter,323.03,1038,53.37,1.244,1.56,-1.44,1.080,-30.73,1.014,10.512,356.18,586,54.78,1.514,1.49,-1.20,1.250,-21.90,1.451,16.264,-7.27,452,51.55,1.017,1.64,-1.74,0.943,-41.03,-0.164,-0.177
20,PGEL,Trend_Filter,318.66,1038,50.29,1.185,2.40,-2.06,1.165,-41.36,0.821,7.705,644.31,584,48.97,1.437,2.63,-1.76,1.492,-27.73,1.342,23.235,-43.75,454,51.98,0.939,2.13,-2.48,0.860,-57.63,-0.394,-0.759
21,MRPL,Momentum_20,303.87,722,51.52,1.248,2.45,-2.13,1.151,-51.41,0.837,5.911,267.88,400,49.50,1.361,3.09,-2.27,1.361,-48.73,0.837,5.497,9.78,322,54.04,1.069,1.73,-1.94,0.891,-28.85,-0.051,0.339
22,OFSS,Momentum_20,284.56,490,53.88,1.475,1.75,-1.41,1.246,-23.58,1.117,12.068,222.80,315,53.33,1.678,1.89,-1.30,1.458,-17.19,1.057,12.961,19.13,175,54.86,1.168,1.52,-1.62,0.937,-15.94,-0.057,1.200
23,TITAGARH,Trend_Filter,283.03,1038,50.67,1.174,2.31,-2.06,1.125,-50.50,0.801,5.605,608.98,507,50.89,1.466,2.72,-1.94,1.398,-37.89,1.331,16.072,-45.98,531,50.47,0.925,1.93,-2.16,0.890,-54.68,-0.524,-0.841
24,INOXWIND,Momentum_20,279.27,771,49.94,1.213,2.57,-2.15,1.197,-64.53,0.817,4.328,573.43,406,50.25,1.549,2.96,-1.94,1.527,-29.29,1.355,19.578,-43.68,365,49.59,0.906,2.14,-2.38,0.896,-71.25,-0.548,-0.613
25,ZENTEC,Trend_Filter,275.73,1038,49.52,1.177,2.32,-1.96,1.184,-47.72,0.782,5.778,563.45,541,47.50,1.446,2.72,-1.72,1.581,-28.57,1.290,19.722,-43.37,497,51.71,0.932,1.92,-2.24,0.856,-68.18,-0.455,-0.636
26,IRFC,Momentum_20,270.42,606,52.64,1.307,2.16,-1.97,1.098,-42.98,0.855,6.292,461.08,330,52.73,1.661,2.83,-2.05,1.384,-33.47,1.216,13.776,-33.98,276,52.54,0.851,1.35,-1.88,0.722,-43.55,-0.762,-0.780
27,HSCL,Momentum_20,267.78,652,49.69,1.263,2.35,-1.85,1.271,-44.86,0.879,5.969,508.45,430,49.53,1.604,2.46,-1.51,1.627,-25.74,1.453,19.753,-39.55,222,50.00,0.859,2.14,-2.52,0.851,-47.90,-0.661,-0.826
28,ANANDRATHI,Trend_Filter,264.94,891,51.96,1.289,1.40,-1.19,1.183,-56.80,1.163,4.664,565.83,647,55.18,1.630,1.46,-1.11,1.315,-34.24,1.935,16.525,-45.19,244,43.44,0.693,1.20,-1.34,0.895,-47.61,-1.485,-0.949
29,DIXON,Momentum_20,264.14,709,54.72,1.284,1.75,-1.67,1.049,-28.50,0.958,9.268,141.74,432,55.56,1.332,1.66,-1.58,1.054,-20.56,0.789,6.894,50.63,277,53.43,1.222,1.90,-1.81,1.048,-20.73,0.295,2.442
30,ADANIPOWER,Trend_Filter,258.75,1038,53.47,1.175,2.15,-2.14,1.008,-62.34,0.758,4.151,605.04,529,51.04,1.463,2.61,-1.89,1.382,-40.49,1.301,14.943,-49.12,509,55.99,0.915,1.72,-2.43,0.710,-74.92,-0.520,-0.656
31,GABRIEL,Trend_Filter,256.58,1038,50.87,1.176,2.14,-1.92,1.116,-38.20,0.776,6.717,622.51,629,50.08,1.435,2.33,-1.66,1.403,-24.72,1.371,25.182,-50.65,409,52.08,0.882,1.87,-2.34,0.799,-51.25,-0.655,-0.988
32,BSE,Trend_Filter,255.38,1038,52.89,1.170,2.23,-2.15,1.034,-65.51,0.747,3.898,891.57,563,53.29,1.494,2.63,-2.03,1.295,-41.66,1.458,21.401,-64.16,475,52.42,0.840,1.75,-2.30,0.759,-76.28,-0.846,-0.841
33,PAYTM,Momentum_20,252.77,645,50.23,1.245,2.52,-2.07,1.218,-43.21,0.877,5.850,139.09,403,49.13,1.288,2.38,-1.81,1.314,-25.46,0.739,5.463,47.55,242,52.07,1.191,2.75,-2.53,1.087,-32.75,0.310,1.452
34,ANURAS,Momentum_20,244.45,515,58.45,1.471,1.40,-1.36,1.026,-31.07,1.166,7.868,222.40,254,59.45,1.963,1.66,-1.27,1.313,-11.26,1.407,19.752,6.84,261,57.47,1.074,1.13,-1.45,0.780,-27.99,-0.194,0.244
35,HUDCO,Momentum_20,239.15,724,50.00,1.229,2.34,-1.94,1.206,-34.18,0.776,6.997,377.91,446,50.67,1.454,2.58,-1.88,1.371,-22.57,1.082,16.744,-29.03,278,48.92,0.917,1.95,-2.03,0.957,-44.81,-0.522,-0.648
36,KALYANKJIL,Trend_Filter,235.00,1038,51.83,1.172,2.07,-1.95,1.063,-40.16,0.746,5.852,450.86,532,53.20,1.427,2.28,-1.84,1.235,-27.12,1.248,16.625,-39.19,506,50.40,0.942,1.84,-2.05,0.897,-55.41,-0.410,-0.707
37,MCX,Trend_Filter,232.27,1038,51.54,1.177,1.87,-1.70,1.100,-36.63,0.797,6.341,630.24,641,53.82,1.462,2.00,-1.61,1.245,-26.79,1.546,23.525,-54.50,397,47.86,0.822,1.64,-1.84,0.891,-60.75,-0.946,-0.897
38,CHENNPETRO,Trend_Filter,228.55,1038,49.13,1.158,2.56,-2.18,1.176,-64.77,0.694,3.529,613.88,608,50.00,1.364,2.94,-2.20,1.333,-46.09,1.147,13.319,-53.98,430,47.91,0.873,2.00,-2.14,0.937,-63.56,-0.699,-0.849
39,GVT&D,Turtle_Breakout,220.13,102,62.75,2.570,3.11,-2.04,1.526,-13.03,1.457,16.894,220.13,102,62.75,2.570,3.11,-2.04,1.526,-13.03,1.457,16.894,0.00,0,0.00,0.000,0.00,0.00,0.000,0.00,0.000,0.000
40,MRPL,Trend_Filter,215.32,1038,52.60,1.164,2.24,-2.19,1.021,-68.83,0.679,3.128,331.96,414,51.69,1.388,3.03,-2.38,1.271,-53.76,0.916,6.175,-27.00,624,53.21,0.984,1.73,-2.06,0.839,-55.34,-0.246,-0.488
41,NAVA,Momentum_20,211.50,713,52.45,1.213,2.31,-2.12,1.090,-41.25,0.721,5.127,335.55,495,52.32,1.370,2.47,-2.01,1.233,-29.37,1.011,11.425,-28.48,218,52.75,0.913,1.93,-2.37,0.817,-41.00,-0.461,-0.695
42,GRSE,Momentum_20,210.98,738,51.36,1.184,2.82,-2.54,1.112,-53.80,0.679,3.922,573.45,455,50.99,1.447,3.13,-2.27,1.378,-33.03,1.189,17.361,-53.82,283,51.94,0.855,2.33,-2.97,0.785,-61.45,-0.663,-0.876
43,JKTYRE,Momentum_20,210.39,740,48.11,1.228,2.09,-1.60,1.307,-34.45,0.790,6.107,153.70,455,46.81,1.294,2.29,-1.57,1.458,-33.40,0.710,4.602,22.34,285,50.18,1.120,1.80,-1.66,1.088,-28.63,0.045,0.780
44,CDSL,Momentum_20,202.36,597,52.60,1.289,1.82,-1.58,1.150,-25.33,0.867,7.989,128.49,343,50.73,1.385,1.90,-1.42,1.337,-22.69,0.775,5.663,32.33,254,55.12,1.177,1.72,-1.83,0.942,-29.48,0.149,1.097
45,TATAINVEST,Turtle_Breakout,192.81,50,62.00,3.564,5.20,-2.38,2.184,-9.72,1.055,19.836,192.81,50,62.00,3.564,5.20,-2.38,2.184,-9.72,1.055,19.836,0.00,0,0.00,0.000,0.00,0.00,0.000,0.00,0.000,0.000
46,TARIL,Trend_Filter,188.61,1036,51.83,1.134,2.85,-2.75,1.037,-48.24,0.631,3.910,873.52,581,50.77,1.395,3.23,-2.41,1.343,-32.26,1.310,27.078,-70.35,455,53.19,0.868,2.40,-3.23,0.742,-79.50,-0.690,-0.885
47,CHENNPETRO,Momentum_20,186.44,728,50.41,1.187,2.60,-2.26,1.148,-48.13,0.652,3.874,346.89,492,51.02,1.353,2.78,-2.19,1.267,-34.80,0.959,9.968,-35.90,236,49.15,0.889,2.21,-2.40,0.920,-49.40,-0.552,-0.727
48,MCX,Momentum_20,183.48,672,52.83,1.220,1.97,-1.83,1.079,-35.03,0.756,5.238,364.39,493,53.55,1.451,2.06,-1.65,1.248,-22.23,1.278,16.392,-38.96,179,50.84,0.785,1.71,-2.29,0.750,-45.65,-0.915,-0.853
49,HAL,Momentum_20,179.76,643,54.43,1.266,1.62,-1.54,1.053,-22.85,0.819,7.867,239.32,439,56.49,1.479,1.67,-1.48,1.133,-17.83,1.112,13.422,-17.55,204,50.00,0.913,1.51,-1.67,0.904,-21.71,-0.630,-0.809
50,GALLANTT,Turtle_Breakout,178.17,67,61.19,2.677,4.29,-2.63,1.632,-12.89,1.039,13.822,178.17,67,61.19,2.677,4.29,-2.63,1.632,-12.89,1.039,13.822,0.00,0,0.00,0.000,0.00,0.00,0.000,0.00,0.000,0.000
51,INOXWIND,Trend_Filter,174.88,1038,50.87,1.138,2.39,-2.21,1.082,-57.13,0.622,3.061,302.86,416,49.76,1.374,2.92,-2.12,1.374,-37.04,0.962,8.177,-31.77,622,51.61,0.983,2.05,-2.27,0.903,-68.25,-0.240,-0.465
52,DIXON,Trend_Filter,174.26,1038,53.95,1.161,1.70,-1.73,0.982,-28.56,0.676,6.101,220.17,498,57.43,1.392,1.60,-1.55,1.027,-17.30,1.048,12.727,-14.34,540,50.74,1.006,1.81,-1.87,0.966,-58.62,-0.169,-0.245
53,ADANIPOWER,Turtle_Breakout,172.68,76,63.16,2.203,4.22,-3.28,1.285,-18.28,0.933,9.447,172.68,76,63.16,2.203,4.22,-3.28,1.285,-18.28,0.933,9.447,0.00,0,0.00,0.000,0.00,0.00,0.000,0.00,0.000,0.000
54,IDEA,EMA21_Mean_Reversion,170.05,142,52.82,1.777,3.33,-2.55,1.303,-19.19,0.943,8.861,72.36,78,47.44,1.770,3.70,-2.28,1.627,-19.19,0.538,3.771,56.68,64,59.38,1.786,2.96,-3.00,0.987,-18.07,0.414,3.137
55,RPOWER,Turtle_Breakout,169.18,67,58.21,2.351,4.78,-2.94,1.628,-19.57,0.994,8.645,169.18,67,58.21,2.351,4.78,-2.94,1.628,-19.57,0.994,8.645,0.00,0,0.00,0.000,0.00,0.00,0.000,0.00,0.000,0.000
56,CHOICEIN,Trend_Filter,166.84,812,54.19,1.238,1.32,-1.28,1.030,-34.19,0.992,4.880,278.36,584,56.68,1.520,1.25,-1.09,1.139,-18.87,1.710,14.751,-29.48,228,47.81,0.853,1.55,-1.68,0.923,-35.04,-0.795,-0.841
57,NEWGEN,Momentum_20,166.31,708,49.86,1.184,2.41,-2.05,1.177,-63.21,0.644,2.631,150.88,407,46.44,1.282,2.64,-1.79,1.472,-32.33,0.700,4.667,6.15,301,54.49,1.067,2.15,-2.46,0.872,-65.17,-0.016,0.094
58,TRENT,Momentum_20,165.06,652,52.91,1.257,1.61,-1.44,1.115,-27.51,0.788,6.000,102.09,429,52.68,1.305,1.51,-1.29,1.167,-33.99,0.639,3.003,31.16,223,53.36,1.186,1.80,-1.73,1.036,-17.55,0.131,1.775
59,HSCL,Turtle_Breakout,162.94,58,55.17,4.392,4.10,-1.15,3.568,-6.14,1.215,26.537,162.94,58,55.17,4.392,4.10,-1.15,3.568,-6.14,1.215,26.537,0.00,0,0.00,0.000,0.00,0.00,0.000,0.00,0.000,0.000
60,APARINDS,Momentum_20,161.77,712,50.42,1.186,2.37,-2.05,1.153,-42.51,0.628,3.805,319.90,545,50.46,1.340,2.39,-1.83,1.306,-34.06,1.024,9.392,-37.66,167,50.30,0.850,2.28,-2.78,0.819,-57.53,-0.561,-0.655
61,SUZLON,Trend_Filter,160.32,1038,49.23,1.133,2.50,-2.33,1.071,-56.13,0.596,2.856,411.46,492,47.76,1.373,2.99,-2.08,1.437,-30.68,1.096,13.411,-49.10,546,50.55,0.933,2.08,-2.59,0.801,-64.84,-0.450,-0.757
62,RPOWER,Momentum_20,155.90,799,47.81,1.146,2.95,-2.50,1.179,-45.89,0.589,3.397,107.64,397,42.57,1.199,3.63,-2.36,1.539,-36.68,0.500,2.935,23.24,402,52.99,1.089,2.41,-2.67,0.900,-49.72,0.138,0.467
63,ELECON,Momentum_20,154.51,761,52.04,1.165,2.32,-2.20,1.056,-46.23,0.608,3.342,272.52,476,52.94,1.339,2.43,-2.07,1.174,-36.12,0.934,7.545,-31.68,285,50.53,0.925,2.13,-2.41,0.886,-34.97,-0.473,-0.906
64,GLAXO,Trend_Filter,154.14,1038,52.41,1.185,1.32,-1.24,1.068,-26.07,0.708,5.912,133.22,398,50.00,1.365,1.77,-1.31,1.351,-16.42,0.793,8.113,8.97,640,53.91,1.053,1.06,-1.19,0.894,-25.08,-0.065,0.358
65,RVNL,Volatility_Breakout,151.76,63,53.97,2.497,5.03,-2.45,2.056,-10.57,0.827,14.357,151.76,63,53.97,2.497,5.03,-2.45,2.056,-10.57,0.827,14.357,0.00,0,0.00,0.000,0.00,0.00,0.000,0.00,0.000,0.000
66,BSOFT,Momentum_20,149.68,694,52.59,1.206,1.74,-1.62,1.077,-29.84,0.713,5.016,101.21,330,52.42,1.364,1.67,-1.36,1.230,-20.30,0.692,4.986,24.09,364,52.75,1.100,1.81,-1.86,0.974,-21.42,0.083,1.125
67,ZENTEC,Turtle_Breakout,147.73,76,52.63,2.345,4.26,-2.02,2.110,-12.14,0.941,12.169,147.73,76,52.63,2.345,4.26,-2.02,2.110,-12.14,0.941,12.169,0.00,0,0.00,0.000,0.00,0.00,0.000,0.00,0.000,0.000
68,POWERINDIA,Momentum_20,146.26,725,51.86,1.179,2.08,-1.92,1.082,-40.42,0.617,3.619,189.53,483,51.76,1.292,2.21,-1.85,1.194,-27.14,0.809,6.984,-14.95,242,52.07,0.974,1.82,-2.06,0.882,-32.67,-0.333,-0.457
69,COCHINSHIP,Turtle_Breakout,145.23,72,56.94,2.939,3.52,-1.59,2.222,-7.67,1.020,18.935,145.23,72,56.94,2.939,3.52,-1.59,2.222,-7.67,1.020,18.935,0.00,0,0.00,0.000,0.00,0.00,0.000,0.00,0.000,0.000
70,INTELLECT,Momentum_20,143.96,734,52.32,1.182,2.00,-1.88,1.059,-35.58,0.610,4.046,88.86,368,51.09,1.250,2.07,-1.76,1.177,-33.30,0.491,2.668,29.18,366,53.55,1.119,1.92,-2.02,0.954,-52.34,0.149,0.557
71,GVT&D,Trend_Filter,140.97,1038,49.90,1.121,2.37,-2.14,1.106,-51.68,0.565,2.728,1167.92,689,52.69,1.446,2.53,-1.97,1.286,-28.10,1.658,41.563,-80.99,349,44.41,0.669,1.97,-2.43,0.811,-81.93,-1.621,-0.989
72,BSOFT,Trend_Filter,139.34,1038,52.79,1.138,1.70,-1.69,1.009,-40.82,0.610,3.414,65.49,300,53.33,1.269,1.70,-1.53,1.111,-35.73,0.434,1.833,44.62,738,52.57,1.092,1.71,-1.75,0.974,-32.12,0.255,1.389
73,NIACL,Momentum_20,136.66,657,49.32,1.187,2.34,-1.98,1.183,-37.71,0.573,3.624,66.93,331,45.62,1.202,2.90,-2.08,1.393,-28.35,0.361,2.361,41.77,326,53.07,1.167,1.86,-1.86,0.999,-26.62,0.232,1.569
74,IOC,Momentum_20,136.30,510,52.55,1.311,1.50,-1.29,1.164,-34.25,0.809,3.980,139.29,331,54.68,1.517,1.51,-1.23,1.232,-21.82,0.980,6.384,-1.25,179,48.60,1.017,1.48,-1.39,1.064,-23.34,-0.415,-0.053
75,CUMMINSIND,Trend_Filter,135.08,1038,52.02,1.160,1.39,-1.31,1.063,-35.04,0.657,3.855,297.20,670,55.07,1.395,1.43,-1.26,1.134,-25.67,1.300,11.578,-40.82,368,46.47,0.828,1.30,-1.37,0.944,-43.15,-0.974,-0.946
76,NBCC,Trend_Filter,132.75,1038,50.87,1.127,2.16,-2.03,1.061,-51.49,0.548,2.578,256.13,483,47.83,1.327,2.67,-1.87,1.430,-30.17,0.886,8.490,-34.64,555,53.51,0.957,1.76,-2.20,0.799,-54.55,-0.386,-0.635
77,RVNL,Turtle_Breakout,129.37,59,57.63,2.181,5.06,-3.16,1.604,-17.33,0.740,7.465,129.37,59,57.63,2.181,5.06,-3.16,1.604,-17.33,0.740,7.465,0.00,0,0.00,0.000,0.00,0.00,0.000,0.00,0.000,0.000
78,SJVN,Trend_Filter,127.27,1038,51.16,1.137,1.91,-1.82,1.047,-50.09,0.541,2.541,205.23,441,49.66,1.336,2.46,-1.87,1.312,-36.45,0.795,5.630,-25.54,597,52.26,0.973,1.52,-1.78,0.855,-45.44,-0.322,-0.562
79,TARIL,Turtle_Breakout,126.03,87,63.22,1.937,3.32,-3.05,1.092,-22.82,0.850,5.523,126.03,87,63.22,1.937,3.32,-3.05,1.092,-22.82,0.850,5.523,0.00,0,0.00,0.000,0.00,0.00,0.000,0.00,0.000,0.000
80,ADANIENT,Momentum_20,123.79,591,53.98,1.221,2.04,-1.96,1.037,-50.56,0.530,2.448,123.14,325,54.46,1.405,1.83,-1.57,1.167,-31.37,0.663,3.925,0.29,266,53.38,1.080,2.29,-2.43,0.943,-50.48,0.001,0.006
81,HSCL,Trend_Filter,123.79,1038,49.23,1.126,2.07,-1.79,1.153,-55.18,0.533,2.243,472.85,599,48.25,1.430,2.25,-1.48,1.519,-37.10,1.294,12.745,-60.93,439,50.57,0.841,1.83,-2.24,0.818,-64.57,-0.859,-0.944
82,ADANIPOWER,Volume_Spike,123.42,66,57.58,2.257,4.24,-2.55,1.663,-22.33,0.743,5.527,123.42,66,57.58,2.257,4.24,-2.55,1.663,-22.33,0.743,5.527,0.00,0,0.00,0.000,0.00,0.00,0.000,0.00,0.000,0.000
83,HINDCOPPER,Momentum_20,121.82,704,50.43,1.158,2.38,-2.12,1.125,-54.11,0.530,2.251,379.46,414,52.17,1.481,2.53,-1.89,1.337,-31.72,1.166,11.963,-53.73,290,47.93,0.828,2.15,-2.41,0.893,-62.40,-0.784,-0.861
84,KAYNES,Momentum_20,120.22,465,52.26,1.220,2.33,-2.12,1.100,-29.41,0.789,4.088,31.17,305,50.49,1.137,2.14,-1.94,1.100,-26.75,0.303,1.165,67.89,160,55.62,1.358,2.67,-2.49,1.068,-25.67,0.626,2.645
85,MAZDOCK,Volume_Spike,119.88,61,59.02,2.734,3.65,-1.92,1.898,-9.78,0.966,12.258,119.88,61,59.02,2.734,3.65,-1.92,1.898,-9.78,0.966,12.258,0.00,0,0.00,0.000,0.00,0.00,0.000,0.00,0.000,0.000
86,TEJASNET,Turtle_Breakout,119.78,39,53.85,2.996,6.16,-2.40,2.568,-14.29,0.766,8.382,119.78,39,53.85,2.996,6.16,-2.40,2.568,-14.29,0.766,8.382,0.00,0,0.00,0.000,0.00,0.00,0.000,0.00,0.000,0.000
87,RRKABEL,Momentum_20,118.99,272,52.94,1.471,1.90,-1.46,1.307,-22.09,1.313,5.386,82.21,125,53.60,1.772,2.22,-1.45,1.534,-12.00,1.277,6.851,20.18,147,52.38,1.223,1.63,-1.46,1.112,-23.14,0.305,0.872
88,BRIGADE,Trend_Filter,118.26,1038,53.76,1.128,1.64,-1.70,0.964,-39.27,0.548,3.012,100.07,471,54.99,1.232,1.67,-1.66,1.008,-24.43,0.573,4.096,9.10,567,52.73,1.048,1.61,-1.73,0.929,-37.13,-0.019,0.245
89,CHOICEIN,Momentum_20,117.88,471,56.48,1.332,1.30,-1.30,1.001,-22.49,0.933,5.241,161.04,366,59.84,1.655,1.16,-1.08,1.073,-16.63,1.515,9.684,-16.53,105,44.76,0.863,1.94,-1.83,1.064,-23.21,-0.702,-0.712
90,ETERNAL,Trend_Filter,117.61,967,52.12,1.125,2.10,-2.06,1.020,-52.33,0.547,2.247,296.30,484,54.13,1.420,1.95,-1.64,1.192,-24.69,1.265,12.001,-45.09,483,50.10,0.942,2.26,-2.45,0.923,-60.51,-0.397,-0.745
91,NEWGEN,Trend_Filter,117.38,1038,51.54,1.120,2.20,-2.11,1.043,-60.84,0.511,1.929,168.43,436,46.79,1.275,2.73,-1.88,1.450,-29.83,0.721,5.646,-19.02,602,54.98,1.010,1.87,-2.31,0.812,-71.98,-0.121,-0.264
92,COLPAL,Trend_Filter,116.95,1038,51.73,1.178,1.08,-0.99,1.090,-27.98,0.689,4.180,99.30,488,54.10,1.346,1.08,-0.95,1.142,-11.29,0.797,8.796,8.85,550,49.64,1.050,1.08,-1.03,1.050,-24.20,-0.144,0.366
93,COFORGE,Momentum_20,115.78,698,50.72,1.188,1.67,-1.46,1.145,-35.28,0.593,3.282,101.57,410,52.20,1.326,1.47,-1.22,1.209,-20.65,0.677,4.918,7.05,288,48.61,1.062,1.96,-1.77,1.107,-32.06,-0.093,0.220
94,BEL,Trend_Filter,115.66,1038,51.35,1.140,1.49,-1.41,1.057,-33.77,0.565,3.425,291.63,682,52.49,1.369,1.56,-1.30,1.201,-24.30,1.187,12.001,-44.93,356,49.16,0.818,1.36,-1.61,0.842,-48.48,-1.022,-0.927
95,GALLANTT,Volume_Spike,115.56,83,56.63,1.892,3.92,-2.78,1.409,-31.85,0.683,3.628,115.56,83,56.63,1.892,3.92,-2.78,1.409,-31.85,0.683,3.628,0.00,0,0.00,0.000,0.00,0.00,0.000,0.00,0.000,0.000

,Strategy,Avg_Return_Per_Asset_pct,Median_Return_pct,Total_Trades_Executed,Profitable_Assets_Count,Average_Win_Rate_pct,Global_Profit_Factor,Avg_Win_Return_pct,Avg_Loss_Return_pct,Win_Loss_Ratio,Sharpe_Ratio,Recovery_Factor,Max_Drawdown_pct,Market_Coverage_Hit_Rate_pct,Long_Avg_Return_Per_Asset_pct,Long_Median_Return_pct,Long_Total_Trades_Executed,Long_Average_Win_Rate_pct,Long_Global_Profit_Factor,Long_Avg_Win_Return_pct,Long_Avg_Loss_Return_pct,Long_Win_Loss_Ratio,Long_Max_Drawdown_pct,Long_Sharpe_Ratio,Long_Recovery_Factor,Long_Profitable_Assets_Count,Long_Market_Coverage_Hit_Rate_pct,Short_Avg_Return_Per_Asset_pct,Short_Median_Return_pct,Short_Total_Trades_Executed,Short_Average_Win_Rate_pct,Short_Global_Profit_Factor,Short_Avg_Win_Return_pct,Short_Avg_Loss_Return_pct,Short_Win_Loss_Ratio,Short_Max_Drawdown_pct,Short_Sharpe_Ratio,Short_Recovery_Factor,Short_Profitable_Assets_Count,Short_Market_Coverage_Hit_Rate_pct
0,Momentum_20,31.65,2.71,245478,250,49.78,1.058,1.80,-1.71,1.049,0.007,1.249,-89.94,52.52,73.05,28.73,145502,49.68,1.187,1.88,-1.58,1.181,-85.56,0.259,3.665,353,74.16,-18.94,-20.16,99976,49.92,0.915,1.69,-1.91,0.901,-82.59,-0.591,-0.321,91,19.12
1,Trend_Filter,6.15,-15.62,441732,185,49.84,1.011,1.62,-1.62,1.002,-0.135,0.347,-93.94,38.87,84.78,33.75,203055,49.61,1.156,1.77,-1.51,1.159,-82.36,0.306,3.670,332,69.75,-37.49,-42.90,238677,50.03,0.906,1.50,-1.71,0.889,-89.83,-0.641,-0.600,40,8.40
2,Volume_Spike,8.23,4.50,22263,268,48.61,1.281,2.44,-2.00,1.266,-0.421,1.331,-73.13,56.30,8.23,4.50,22263,48.61,1.281,2.44,-2.00,1.266,-73.13,-0.421,1.331,268,56.30,0.00,0.00,0,0.00,0.000,0.00,0.00,0.000,0.00,0.000,0.000,0,0.00
3,Turtle_Breakout,11.86,3.28,26387,286,49.67,1.266,2.02,-1.65,1.221,-0.423,1.529,-83.98,60.08,11.86,3.28,26387,49.67,1.266,2.02,-1.65,1.221,-83.98,-0.423,1.529,286,60.08,0.00,0.00,0,0.00,0.000,0.00,0.00,0.000,0.00,0.000,0.000,0,0.00
4,EMA21_Mean_Reversion,-3.07,-2.32,57743,217,50.67,1.025,1.82,-1.95,0.966,-0.476,0.350,-89.52,45.59,8.41,6.59,21245,51.03,1.329,2.12,-1.84,1.194,-63.04,-0.455,1.124,327,68.70,-10.41,-7.30,36498,50.46,0.950,1.64,-2.02,0.873,-90.25,-0.822,-0.013,171,35.92
5,MACD_Histogram_Momentum,6.81,3.64,17757,290,49.85,1.348,1.85,-1.52,1.264,-0.673,1.204,-38.37,60.92,6.81,3.64,17757,49.85,1.348,1.85,-1.52,1.264,-38.37,-0.673,1.204,290,60.92,0.00,0.00,0,0.00,0.000,0.00,0.00,0.000,0.00,0.000,0.000,0,0.00
6,Volatility_Breakout,6.67,2.17,11711,267,48.94,1.411,2.52,-1.92,1.364,-0.696,1.405,-41.54,56.09,6.67,2.17,11711,48.94,1.411,2.52,-1.92,1.364,-41.54,-0.696,1.405,267,56.09,0.00,0.00,0,0.00,0.000,0.00,0.00,0.000,0.00,0.000,0.000,0,0.00
7,Bollinger_Mean_Reversion,3.44,1.98,11331,267,49.52,1.384,1.87,-1.58,1.266,-0.978,1.091,-30.70,56.09,3.44,1.98,11331,49.52,1.384,1.87,-1.58,1.266,-30.70,-0.978,1.091,267,56.09,0.00,0.00,0,0.00,0.000,0.00,0.00,0.000,0.00,0.000,0.000,0,0.00
8,Support_Bounce,6.21,5.82,9827,330,52.23,1.852,1.79,-1.38,1.413,-0.979,1.791,-32.03,69.33,6.21,5.82,9827,52.23,1.852,1.79,-1.38,1.413,-32.03,-0.979,1.791,330,69.33,0.00,0.00,0,0.00,0.000,0.00,0.00,0.000,0.00,0.000,0.000,0,0.00
9,EMA_Crossover,5.04,3.63,9595,313,50.77,1.685,1.85,-1.42,1.395,-1.061,1.575,-46.26,65.76,5.04,3.63,9595,50.77,1.685,1.85,-1.42,1.395,-46.26,-1.061,1.575,313,65.76,0.00,0.00,0,0.00,0.000,0.00,0.00,0.000,0.00,0.000,0.000,0,0.00
10,RSI_Overbought,-2.02,-1.36,9026,202,49.18,1.166,1.70,-1.87,1.034,-1.333,0.371,-38.64,42.44,0.00,0.00,0,0.00,0.000,0.00,0.00,0.000,0.00,0.000,0.000,0,0.00,-2.02,-1.36,9026,49.18,1.166,1.70,-1.87,1.034,-38.64,-1.333,0.371,202,42.44
11,RSI_Oversold,3.34,2.56,5086,316,53.30,2.717,2.07,-1.67,1.572,-1.445,2.466,-28.76,66.39,3.34,2.56,5086,53.30,2.717,2.07,-1.67,1.572,-28.76,-1.445,2.466,316,66.39,0.00,0.00,0,0.00,0.000,0.00,0.00,0.000,0.00,0.000,0.000,0,0.00
12,BB_Squeeze_Breakout,1.76,0.50,4087,251,49.35,2.256,2.02,-1.63,1.622,-1.900,1.919,-28.84,52.73,1.76,0.50,4087,49.35,2.256,2.02,-1.63,1.622,-28.84,-1.900,1.919,251,52.73,0.00,0.00,0,0.00,0.000,0.00,0.00,0.000,0.00,0.000,0.000,0,0.00
13,SuperTrend_Mimic,0.34,-0.55,1373,180,46.18,2.246,3.42,-2.85,1.409,-2.944,1.734,-46.03,37.82,0.34,-0.55,1373,46.18,2.246,3.42,-2.85,1.409,-46.03,-2.944,1.734,180,37.82,0.00,0.00,0,0.00,0.000,0.00,0.00,0.000,0.00,0.000,0.000,0,0.00
14,Golden_Cross,0.22,0.14,1214,226,51.48,5.470,1.27,-1.18,2.531,-8.444,1.562,-12.08,47.48,0.22,0.14,1214,51.48,5.470,1.27,-1.18,2.531,-12.08,-8.444,1.562,226,47.48,0.00,0.00,0,0.00,0.000,0.00,0.00,0.000,0.00,0.000,0.000,0,0.00